<?php

/*
 * Cities of Bangladesh
 * Author: Md Rasel Khan <hello@raselnotes.com> | https://raselnotes.com
 * Version: 1.0.0
 * License: http://opensource.org/licenses/gpl-license.php GNU Public License
 */

global $places;

$places['BD'] = array(
    'BD-05' => array(
        "Bagerhat Sadar",
        "Chitalmari",
        "Fakirhat",
        "Kachua",
        "Mollahat",
        "Mongla",
        "Morrelganj",
        "Rampal",
        "Sarankhola",
    ),
    'BD-01' => array(
        "Alikadam",
        "Bandarban Sadar",
        "Lama",
        "Naikhongchhari",
        "Rowangchhari",
        "Ruma",
        "Thanchi",
    ),
    'BD-02' => array(
        "Amtali",
        "Bamna",
        "Barguna Sadar",
        "Betagi",
        "Patharghata",
        "Taltali",
    ),
    'BD-06' => array(
        "Agailjhara",
        "Babuganj",
        "Bakerganj",
        "Banari Para",
        "Gaurnadi",
        "Hizla",
        "Barisal Sadar (Kotwali)",
        "Mhendiganj",
        "Muladi",
        "Wazirpur",
    ),
    'BD-07' => array(
        "Bhola Sadar",
        "Burhanuddin",
        "Char Fasson",
        "Daulat Khan",
        "Lalmohan",
        "Manpura",
        "Tazumuddin",
    ),
    'BD-03' => array(
        "Adamdighi",
        "Bogra Sadar",
        "Dhunat",
        "Dhupchanchia",
        "Gabtali",
        "Kahaloo",
        "Nandigram",
        "Sariakandi",
        "Shajahanpur",
        "Sherpur",
        "Shibganj",
        "Sonatola",
    ),
    'BD-04' => array(
        "Akhaura",
        "Banchharampur",
        "Bijoynagar",
        "Brahmanbaria Sadar",
        "Ashuganj",
        "Kasba",
        "Nabinagar",
        "Nasirnagar",
        "Sarail",
    ),
    'BD-09' => array(
        "Chandpur Sadar",
        "Faridganj",
        "Haim Char",
        "Hajiganj",
        "Kachua",
        "Matlab Dakshin",
        "Matlab Uttar",
        "Shahrasti",
    ),
    'BD-10' => array(
        "Anowara",
        "Bayejid Bostami",
        "Banshkhali",
        "Bakalia",
        "Boalkhali",
        "Chandanaish",
        "Chandgaon",
        "Chattogram Port",
        "Double Mooring",
        "Fatikchhari",
        "Halishahar",
        "Hathazari",
        "Kotwali",
        "Khulshi",
        "Lohagara",
        "Mirsharai",
        "Pahartali",
        "Panchlaish",
        "Patiya",
        "Patenga",
        "Rangunia",
        "Raozan",
        "Sandwip",
        "Satkania",
        "Sitakunda",
        "Agrabad ",
    ),
    'BD-12' => array(
        "Alamdanga",
        "Chuadanga Sadar",
        "Damurhuda",
        "Jiban Nagar",
    ),
    'BD-11' => array(
        "Chakaria",
        "Cox's Bazar Sadar",
        "Kutubdia",
        "Maheshkhali",
        "Pekua",
        "Ramu",
        "Teknaf",
        "Ukhiya Upazila",
    ),
    'BD-08' => array(
        "Barura",
        "Brahman Para",
        "Burichang",
        "Chandina",
        "Chauddagram",
        "Cumilla Sadar Dakshin",
        "Daudkandi",
        "Debidwar",
        "Homna",
        "Cumilla Adarsha Sadar",
        "Laksam",
        "Manoharganj",
        "Meghna",
        "Muradnagar",
        "Nangalkot",
        "Titas",
    ),
    'BD-13' => array(
        "12 Tala",
        "Aam Bagan",
        "Abdullah Bag",
        "Abujar Bafari Gali",
        "Abul Hotel",
        "Addin Hospital",
        "Adorsho Nagor",
        "Aftab Nagor Block A To G",
        "Agora",
        "Alen Bari",
        "Arambag",
        "Arjot Para",
        "Ashalota, Bonolota",
        "Aurongojeb Road",
        "Baf Shaheen College/Jahangir Gate",
        "Baganbari",
        "Banani",
        "Banani 1",
        "Banani 11",
        "Banani 17",
        "Banani 2",
        "Banani 21",
        "Banani 23",
        "Banani 27",
        "Banani 8",
        "Banani Chairman Bari",
        "Banani Dohs",
        "Bangshal",
        "Bashtola",
        "Bashundhara Block  A To L",
        "Bata Gali",
        "Begun Bari ",
        "Bepari Gali",
        "Bg Press",
        "Bhauya Para",
        "Biam Auditorium",
        "Bibirbagicha",
        "Bongsal",
        "Dhoar",
        "Boro Moghbazar",
        "Center Point",
        "Chairman Gali",
        "Channel 24",
        "Christian Para",
        "Cid Office",
        "Comilla Para",
        "Dalibari Kachabazar",
		"Dhamrai",
        "Demra",
        "Dillu Road",
        "Diplomatic Zone",
        "Dit Project",
        "Dnc Staff Quarter",
        "Doctor Goli",
		"Dohar",
        "Dokkhin Para",
        "East Goran",
        "East Nakhal Para",
        "East Noyatola",
        "East Rumpura",
        "Eskaton",
        "Fasertake",
        "Gm Bari",
        "Goran",
        "Graveyard Road",
        "Green Way",
        "Gudara Ghat",
        "Old Dhaka",
        "Gulbag",
        "Gulshan",
        "Gulshan 1",
        "Gulshan 2",
        "Gulshan Arong",
        "Gulshan Avenue",
        "Gupi Para",
        "Hazari Bari",
        "Imam Bag",
        "Jagonnath Pur",
        "Jourshara And Lichu Bagan",
        "Jurain",
        "Kajla",
        "Kakoli",
        "Kalachad Pur And Norda",
        "Kazi Office R Gali",
        "Kemal Ataturk Avenue",
        "Khilbarir Take",
        "Khilgaon",
        "Khilgaon Block A",
        "Khilgaon Block B",
        "Khilgaon Block C",
        "Krishi Market",
        "Kuni Para",
        "Kunipara",
        "Kuril Bisso Road",
        "Kuril Chaurasta",
        "Kuril Ghatpar",
        "Lalbag",
        "Lalmatia",
        "Link Road",
        "Lukaser Mor",
        "Maasranga Television",
        "Mailbag 1st Line",
        "Malibag",
        "Malibag Chowdhuripara",
        "Malitola",
        "Marul Badda",
        "Mirbag",
        "Mogbazar",
        "Mohakhali Bus Terminal",
        "Mohammadia Housing Limited",
        "Mohammadia Housing Ltd",
        "Mohammadpur",
        "Mohanagor Project",
        "Moinar Bag",
        "Monipuripara",
        "Motijheel",
        "Mouchak",
        "Navy Headquarters",
		"Nawabganj (Dhaka)",
        "Nazimuddir Road",
        "Newmarket",
        "Nijhum Officers Quarters",
        "Niketon",
        "Nobin Bag",
        "Nobodoy Housing Ltd",
        "North Goran",
        "Notun Bag",
        "Nurjahan Road",
        "Paglamajar Gali",
        "Pakistan Embassy",
        "Panthapath",
        "Pc Culture Housing",
        "Police Plaza",
        "Post Office Road",
        "Postogola",
        "Prime Minister Office",
        "Prodan Muntri Karjaloy",
        "Provati Bag",
        "Purba Anchol Road",
        "Qatwali",
        "Radisson Water Blu Hotel",
        "Rajabazar",
        "Rampura Banassre",
        "Rampura Bazar",
        "Rampura Hazipara",
        "Rangs Vaban",
        "Razia Sultana Road",
        "Riaz Bag",
        "Roma Century ",
        "Rosulbag",
        "Sadhinata Tower",
        "Santibag",
        "Satrasta",
        "Satta Gali",
		"Savar",
        "Sayed Nagor",
        "Shadhinota Sharoni",
        "Shahbag",
        "Shahidbag",
        "Shankar",
        "Shanti Niketon",
        "Shatar Kul",
        "Shekerteak",
        "Sheron Bag",
        "Shersah Suri Road",
        "Shubastu Najor Velly",
        "Shyamoli",
        "Siddiq Master Dhal",
        "Sipahi Bag",
        "Sismohol",
        "Soilmaid",
        "Soinik Club",
        "South Badda",
        "South Banassre",
        "South Goran",
        "Sukrabad",
        "Sur Soyad Road",
        "T&T Colony",
        "T&T Gali",
        "Tajmahal Road",
        "Taltola",
        "Tejgaon Industrial Area",
        "Tejgaon Link Road",
        "Tejgaon Truck Stand",
        "Tibet",
        "Town Hall",
        "Truck Stand",
        "United Hospital ",
        "Uttorpara",
        "Vatara",
        "Vodro Gali",
        "Vootergoli",
        "West Mailbag",
        "West Nakhal Para",
        "West Panthapath",
        "West Rumpura",
        "Wreless Gate",
        "Zigatala",
        "Baridhara",
        "Rampura",
        "Banasree",
        "Bashabo",
        "Moghbazar",
        "Tejgaon",
        "Mohakhali",
        "Mohakhali Dohs",
        "Banani",
        "Bashundhara R/A",
        "Notun Bazar",
        "Shahjadpur",
        "Norda",
        "Nakhalpara",
        "Farmgate",
        "Azimpur",
        "Dhaka University",
        "Kalabagan",
        "Elephant Road",
        "Asad Gate",
        "Hazaribag",
        "Adabar",
        "Chankharpul",
        "Nazimuddin Road",
        "Kamrangirchor",
        "Jatrabari",
        "Shantinagar",
        "Mugdapara",
        "Chakbazar",
        "Maniknagar",
        "Kamalapur",
        "Golapbag",
        "Paltan",
        "Gopibag",
        "Kakrail",
        "Tikatuli",
        "Shonir Akhra",
        "Gendaria",
        "Mirpur",
        "Mirpur 1",
        "Mirpur 2",
        "Mirpur 6",
        "Mirpur 7",
        "Mirpur 11",
        "Mirpur 12",
        "Mirpur Dohs",
        "Mirpur 10",
        "Mirpur 13",
        "Mirpur 14",
        "Kalshi",
        "Agargaon",
        "Shewrapara",
        "Kazipara",
        "Mirpur Cantonment",
        "Kallaynnpur",
        "Darus Salam",
        "Azampur",
        "Nikunjo 1",
        "Khilkhet",
        "Uttar Khan/Dakkhin Khan",
        "Kafrul",
        "Baridhara",
        "Baridhara Dohs",
        "Baridhara Block-J",
        "Shajadpur East",
        "Kuril",
        "Shipahibag",
        "Meradia",
        "Dhanmondi",
        "Dhanmondi 9a",
        "Dhanmondi R/A",
        "Dhanmondi 9",
        "Dhanmondi 8a",
        "Dhanmondi 8",
        "Dhanmondi 1",
        "Dhanmondi 2",
        "Dhanmondi 11a",
        "Dhanmondi 12a",
        "Dhanmondi 10a",
        "Dhanmondi 1a",
        "Dhanmondi 2a",
        "Dhanmondi 3",
        "Dhanmondi 4",
        "Dhanmondi 3a",
        "Dhanmondi 4a",
        "Dhanmondi 5a",
        "Dhanmondi 5",
        "Dhanmondi 6",
        "Dhanmondi 6a",
        "Dhanmondi 7",
        "Dhanmondi 7a",
        "Dhanmondi 10",
        "Dhanmondi 11",
        "Dhanmondi 12",
        "Dhanmondi 13",
        "Dhanmondi 16",
        "Dhanmondi 13a",
        "Dhanmondi 14a",
        "Dahnmondi 15a",
        "Dhanmondi 14",
        "Dhanmondi 15",
        "Dhanmondi 27",
        "Dhanmondi 31",
        "Dhanmondi 30",
        "Dhanmondi 32",
        "Green Road",
        "Vasan Tek",
        "Jakir Hussain Road",
        "Senpara",
        "Bais Teki",
        "Kochukhet",
        "Ibrahimpur",
        "Balughat",
        "Matikata",
        "Janata Housing",
        "Eastern Housing",
        "Pallabi",
        "Rupnagor",
        "Ahamedbag",
        "Tolarbag",
        "Ansar Camp",
        "Golarteak",
        "Pirerbag",
        "Paikpara",
        "Mazar Road",
        "Uttara",
        "Uttara Sector 1",
        "Uttara Sector 3",
        "Uttara Sector 4",
        "Uttara Sector 5",
        "Uttara Sector 6",
        "Uttara Sector 8",
        "Uttara Sector 7",
        "Uttara Sector 9",
        "Uttara Sector 10",
        "Uttara Sector 11",
        "Uttara Sector 12",
        "Uttara Sector 13",
        "Uttara Sector 14",
        "Uttara Jasimuddin",
        "Lake City",
        "Ashkona",
        "Nondipara",
        "Wari",
        "Foridabad",
        "Sadarghat",
        "Gulistan",
        "Nawabpur",
        "Lakshmibazar",
        "Shajahanpur",
        "Shutrapur",
        "Fokirapool",
        "Hazipara",
        "Baily Road",
        "Shaheenbag",
        "Rajarbag",
        "Abdullahpur",
        "Mirpur",
        "Badda",
        "Middle Badda",
        "North Badda",
        "Bordhon Bari",
        "West Rampura",
        "Kalachandpur",
        "Nurerchala",
        "Gopipara",
        "Manda",
        "Bongshal",
        "Bashundhara 300ft",
        "Kaderabad Housing",
        "Chan Mia Housing",
        "Mohanogor Project",
        "Dhanmondi 28",
        "Dhaka Housing",
        "Iqbal Road",
        "Asad Avenue",
        "Aziz Mohollah",
        "Babar Road",
        "Old Airport Road",
        "Bfdc Mor",
        "Shahjanpur",
        "Shonargoan",
        "Tejturi Bazar",
        "Kawran Bazar",
        "Fdc",
        "Noyatola",
        "Peyarabag",
        "Pollima",
        "Ansar Camp(Moghbazar)",
        "Khilgaon Taltola",
        "Tilpa Para",
        "Modhubag",
        "Ulon",
        "Aftab Nagar",
        "Shatarkul",
        "Jamuna Future Park",
        "Aziz Sarani",
        "Coca-Cola",
        "Apollo Hospital",
        "Shoinik Club",
        "Bangladesh Betar",
        "Monipur",
        "Sony Cienema Hall",
        "South Bishil",
        "Bangla College",
        "Tolar Bag",
        "Technical",
        "Gabtoli",
        "Nikunjo 2",
        "Namapara",
        "Pink City",
        "Kawla",
        "Airport",
        "Haji Camp",
        "Koshai Bari",
        "Mollar Tek",
        "Prem Bagan",
        "Gawair",
        "Azampur Kacha Bazar",
        "Chalabon",
        "Rajlakhsmi",
        "House Building",
        "Diya Bari",
        "Uttara Residential Model Town",
        "Faydabad",
        "Kamarpara",
        "Baitul Aman Housing",
        "Bashbari",
        "Chand Uddan",
        "Geneva Camp",
        "Humayun Road",
        "Solimullah Road",
        "Sher Shah Suri Road",
        "Jafrabad",
        "Katasur",
        "Mohammadpur Thana (New)",
        "Rayer Bazar",
        "Modhu Bazar",
        "Khamar Bari",
        "Manik Mia Avenue",
        "Sobhanbag",
        "Tallabag",
        "West Razabazar",
        "Indira Road",
        "East Razabazar",
        "Kathalbagan",
        "Cresent Road",
        "North Road",
        "Central Road",
        "Hatirpool",
        "Paribag",
        "Science Lab",
        "Nilkhet",
        "Pilkhana",
        "Gonok Tuli",
        "Borhanpur",
        "Polashi",
        "Bakshi Bazar",
        "Baridhara Diplomatic",
        "Tb Gate",
        "Rasulbag",
        "Amtoli",
        "Korail Bosti",
        "Mohakhali Wireless",
        "Elenbari",
        "West Nakhalpara",
        "East Nakhalpara",
        "Nabisco",
        "Jahangir Gate",
        "Arjatpara",
        "Tejgaon Old Airport",
        "Joarsahara",
        "Banani (Chairman Bari)",
        "Mintu Road",
        "Shideshwari",
        "Shobujbag",
        "Basabo Patwary Goli",
        "Mather Tek",
        "Matuwail",
        "Dhonia",
        "Madinabag",
        "Rayerbag",
        "Islampur",
        "Patuatuli",
        "Shammibag",
        "Bonogram",
        "Tatibazar",
        "Kotowali",
        "Babubazar",
        "Mitford",
        "Nayabazar",
        "Chokbazar",
        "Siddiqbazar",
        "Saydabad",
        "Dilkusha",
        "Baytul Mokarrom",
        "Gpo",
        "Press Club",
        "Bijay Nagar",
        "Shegunbagicha",
        "Aga Sadiq Road",
        "Urdu Road",
        "Begumbazar",
        "Armanitola",
        "Nazirabazar",
        "Boro Shahebr Bazar",
        "Jagannath University",
        "Shakharibazar",
        "Narinda",
        "Chowdhury Para",
        "Kuratoli",
        "Bijoy Sharanani",
        "Demra",
        "Postogola",
        "Jurain",
        "Kajla",
        "Bibirbagicha",
        "Keraniganj Upazila Sadar",
    ),
    'BD-14' => array(
        "Birampur",
        "Birganj",
        "Biral",
        "Bochaganj",
        "Chirirbandar",
        "Fulbari",
        "Ghoraghat",
        "Hakimpur",
        "Kaharole",
        "Khansama",
        "Dinajpur Sadar",
        "Nawabganj",
        "Parbatipur",
    ),
    'BD-15' => array(
        "Alfadanga",
        "Bhanga",
        "Boalmari",
        "Char Bhadrasan",
        "Faridpur Sadar",
        "Madhukhali",
        "Nagarkanda",
        "Sadarpur",
        "Saltha",
    ),
    'BD-16' => array(
        "Feni Sadar",
        "Daganbhuiyan ",
        "Chhagalnaiya",
        "Sonagaz",
        "Parshuram",
        "Fulgazi",
    ),
    'BD-19' => array(
        "Fulchhari",
        "Gaibandha Sadar",
        "Gobindaganj",
        "Palashbari",
        "Sadullapur",
        "Saghata",
        "Sundarganj",
    ),
    'BD-18' => array(
        "Gazipur Sadar",
        "Kaliakair",
        "Kaliganj",
        "Kapasia",
        "Sreepur",
        "Tongi",
    ),
    'BD-17' => array(
        "Gopalganj Sadar",
        "Kashiani",
        "Kotalipara",
        "Muksudpur",
        "Tungipara",
    ),
    'BD-20' => array(
        "Ajmiriganj",
        "Bahubal",
        "Baniachong",
        "Chunarughat",
        "Habiganj Sadar",
        "Lakhai",
        "Madhabpur",
        "Nabiganj",
    ),
    'BD-21' => array(
        "Bakshiganj",
        "Dewanganj",
        "Islampur",
        "Jamalpur Sadar",
        "Madarganj",
        "Melandaha",
        "Sarishabari Upazila",
    ),
    'BD-22' => array(
        "Abhaynagar",
        "Bagher Para",
        "Chaugachha",
        "Jhikargachha",
        "Keshabpur",
        "Jashore Sadar",
        "Manirampur",
        "Sharsha",
        "Benapole",
    ),
    'BD-25' => array(
        "Jhalokati Sadar",
        "Kanthalia",
        "Nalchity",
        "Rajapur",
    ),
    'BD-23' => array(
        "Harinakunda",
        "Jhenaidah Sadar",
        "Kaliganj",
        "Kotchandpur",
        "Maheshpur",
        "Shailkupa",
    ),
    'BD-24' => array(
        "Akkelpur",
        "Joypurhat Sadar",
        "Kalai",
        "Khetlal",
        "Panchbibi",
    ),
    'BD-29' => array(
        "Dighinala",
        "Khagrachhari Sadar",
        "Lakshmichhari",
        "Mahalchhari",
        "Manikchhari",
        "Matiranga",
        "Panchhari",
        "Ramgarh",
    ),
    'BD-27' => array(
        "Batiaghata",
        "Dacope",
        "Daulatpur",
        "Dumuria",
        "Dighalia",
        "Khalishpur",
        "Khan Jahan Ali",
        "Khulna Sadar",
        "Koyra",
        "Paikgachha",
        "Phultala",
        "Rupsa",
        "Sonadanga",
        "Terokhada",
    ),
    'BD-26' => array(
        "Austagram",
        "Bajitpur",
        "Bhairab",
        "Hossainpur",
        "Itna",
        "Karimganj",
        "Katiadi",
        "Kishoreganj Sadar",
        "Kuliar Char",
        "Mithamain",
        "Nikli",
        "Pakundia",
        "Tarail",
    ),
    'BD-28' => array(
        "Bhurungamari",
        "Char Rajibpur",
        "Chilmari",
        "Phulbari",
        "Kurigram Sadar",
        "Nageshwari",
        "Rajarhat",
        "Raumari",
        "Ulipur",
    ),
    'BD-30' => array(
        "Bheramara",
        "Daulatpur",
        "Khoksa",
        "Kumarkhali",
        "Kushtia Sadar",
        "Mirpur",
    ),
    'BD-31' => array(
        "Kamalnagar",
        "Lakshmipur Sadar",
        "Roypur",
        "Ramganj",
        "Ramgati",
    ),
    'BD-32' => array(
        "Aditmari",
        "Hatibandha",
        "Kaliganj",
        "Lalmonirhat Sadar",
        "Patgram",
    ),
    'BD-36' => array(
        "Kalkini",
        "Madaripur Sadar",
        "Rajoir",
        "Shibchar",
    ),
    'BD-37' => array(
        "Magura Sadar",
        "Mohammadpur",
        "Shalikha",
        "Sreepur",
    ),
    'BD-33' => array(
        "Daulatpur",
        "Ghior",
        "Harirampur",
        "Manikganj Sadar",
        "Saturia",
        "Shibalaya",
        "Singair",
    ),
    'BD-39' => array(
        "Gangni",
        "Mujib Nagar",
        "Meherpur Sadar",
    ),
    'BD-38' => array(
        "Barlekha",
        "Juri",
        "Kamalganj",
        "Kulaura",
        "Moulvibazar Sadar",
        "Rajnagar",
        "Sreemangal",
    ),
    'BD-35' => array(
        "Gazaria",
        "Lohajang",
        "Munshiganj Sadar",
        "Serajdikhan",
        "Sreenagar",
        "Tongibari",
    ),
    'BD-34' => array(
        "Bhaluka",
        "Dhobaura",
        "Fulbaria",
        "Gaffargaon",
        "Gauripur",
        "Haluaghat",
        "Ishwarganj",
        "Mymensingh Sadar",
        "Muktagachha",
        "Nandail",
        "Phulpur",
        "Trishal",
    ),
    'BD-48' => array(
        "Atrai",
        "Badalgachhi",
        "Dhamoirhat",
        "Manda",
        "Mahadebpur",
        "Naogaon Sadar",
        "Niamatpur",
        "Patnitala",
        "Porsha",
        "Raninagar",
        "Sapahar",
    ),
    'BD-43' => array(
        "Kalia",
        "Lohagara",
        "Narail Sadar",
    ),
    'BD-40' => array(
        "Araihazar",
        "Sonargaon",
        "Bandar",
        "Narayanganj Sadar",
        "Rupganj",
    ),
    'BD-42' => array(
        "Belabo",
        "Manohardi",
        "Narsingdi Sadar",
        "Palash",
        "Roypura",
        "Shibpur",
    ),
    'BD-44' => array(
        "Bagatipara",
        "Baraigram",
        "Gurudaspur",
        "Lalpur",
        "Natore Sadar",
        "Singra",
    ),
    'BD-45' => array(
        "Bholahat",
        "Gomastapur",
        "Nachole",
        "Chapai Nababganj Sadar",
        "Shibganj",
    ),
    'BD-41' => array(
        "Atpara",
        "Barhatta",
        "Durgapur",
        "Khaliajuri",
        "Kalmakanda",
        "Kendua",
        "Madan",
        "Mohanganj",
        "Netrokona Sadar",
        "Purbadhala",
    ),
    'BD-46' => array(
        "Dimla Upazila",
        "Domar Upazila",
        "Jaldhaka Upazila",
        "Kishoreganj Upazila",
        "Nilphamari Sadar Upaz",
        "Saidpur Upazila",
    ),
    'BD-47' => array(
        "Begumganj",
        "Chatkhil",
        "Companiganj",
        "Hatiya",
        "Kabirhat",
        "Senbagh",
        "Sonaimuri",
        "Subarnachar",
        "Noakhali Sadar",
    ),
    'BD-49' => array(
        "Atgharia",
        "Bera",
        "Bhangura",
        "Chatmohar",
        "Faridpur",
        "Ishwardi",
        "Pabna Sadar",
        "Santhia",
        "Sujanagar",
    ),
    'BD-52' => array(
        "Atwari",
        "Boda",
        "Debiganj",
        "Panchagarh Sadar",
        "Tentulia",
    ),
    'BD-51' => array(
        "Bauphal",
        "Dashmina",
        "Dumki",
        "Galachipa",
        "Kalapara",
        "Mirzaganj",
        "Patuakhali Sadar",
        "Rangabali",
    ),
    'BD-50' => array(
        "Bhandaria",
        "Kawkhali",
        "Mathbaria",
        "Nazirpur",
        "Pirojpur Sadar",
        "Nesarabad (Swarupkati)",
        "Zianagar",
    ),
    'BD-53' => array(
        "Baliakandi",
        "Goalanda",
        "Kalukhali",
        "Pangsha",
        "Rajbari Sadar",
    ),
    'BD-54' => array(
        "Bagha",
        "Baghmara",
        "Boalia",
        "Charghat",
        "Durgapur",
        "Godagari",
        "Matihar",
        "Mohanpur",
        "Paba",
        "Puthia",
        "Rajpara",
        "Shah Makhdum",
        "Tanore",
    ),
    'BD-56' => array(
        "Baghaichhari",
        "Barkal Upazila",
        "Kawkhali (Betbunia)",
        "Belai Chhari Upazi",
        "Kaptai Upazila",
        "Jurai Chhari Upazil",
        "Langadu Upazila",
        "Naniarchar Upazila",
        "Rajasthali Upazila",
        "Rangamati Sadar Upazila",
    ),
    'BD-55' => array(
        "Badarganj",
        "Gangachara",
        "Kaunia",
        "Rangpur Sadar",
        "Mitha Pukur",
        "Pirgachha",
        "Pirganj",
        "Taraganj",
    ),
    'BD-58' => array(
        "Assasuni",
        "Debhata",
        "Kalaroa",
        "Kaliganj",
        "Satkhira Sadar",
        "Shyamnagar",
        "Tala",
    ),
    'BD-62' => array(
        "Bhedarganj",
        "Damudya",
        "Gosairhat",
        "Naria",
        "Shariatpur Sadar",
        "Zanjira",
    ),
    'BD-57' => array(
        "Jhenaigati",
        "Nakla",
        "Nalitabari",
        "Sherpur Sadar",
        "Sreebardi",
    ),
    'BD-59' => array(
        "Belkuchi",
        "Chauhali",
        "Kamarkhanda",
        "Kazipur",
        "Royganj",
        "Shahjadpur",
        "Sirajganj Sadar",
        "Tarash",
        "Ullah Para",
    ),
    'BD-61' => array(
        "Bishwambarpur",
        "Chhatak",
        "Dakshin Sunamganj",
        "Derai",
        "Dharampasha",
        "Dowarabazar",
        "Jagannathpur",
        "Jamalganj",
        "Sulla",
        "Sunamganj Sadar",
        "Tahirpur",
    ),
    'BD-60' => array(
        "Balaganj",
        "Beani Bazar",
        "Bishwanath",
        "Companiganj",
        "Dakshin Surma",
        "Fenchuganj",
        "Golapganj",
        "Gowainghat",
        "Jaintiapur",
        "Kanaighat",
        "Sylhet Sadar",
        "Zakiganj",
    ),
    'BD-63' => array(
        "Basail",
        "Bhuapur",
        "Delduar",
        "Dhanbari",
        "Ghatail",
        "Gopalpur",
        "Kalihati",
        "Madhupur",
        "Mirzapur",
        "Nagarpur",
        "Sakhipur",
        "Tangail Sadar",
    ),
    'BD-64' => array(
        "Baliadangi",
        "Haripur",
        "Pirganj",
        "Ranisankail",
        "Thakurgaon Sadar",
    ),
);
